Repository Bakery-EFUB/Bakery-Back, pull requests merged in 2022-07, with the labels that each got.

#10 New: 유저 API 및 s3 업로드/다운로드 기능
  build.gradle
  src/main/java/bakery/caker/controller/MemberController.java
  src/main/java/bakery/caker/domain/Member.java
  src/main/java/bakery/caker/dto/MemberRequestDTO.java
  src/main/java/bakery/caker/dto/MemberResponseDTO.java
  src/main/java/bakery/caker/service/ImageUploadService.java
  src/main/java/bakery/caker/service/MemberService.java
  src/main/java/bakery/caker/service/OAuthUserService.java
Labels: enhancement, new feature

#16 Refactor: createCredentials() & createPresigner() 리팩토링
  src/main/java/bakery/caker/service/ImageUploadService.java
  src/main/java/bakery/caker/service/MemberService.java
Labels: enhancement

#14 New: Comment, Order api 추가
  src/main/java/bakery/caker/CakerApplication.java
  src/main/java/bakery/caker/controller/SheetController.java
  src/main/java/bakery/caker/domain/BaseTimeEntity.java
  src/main/java/bakery/caker/domain/Comment.java
  src/main/java/bakery/caker/domain/Recomment.java
  src/main/java/bakery/caker/domain/Sheet.java
  src/main/java/bakery/caker/dto/CommentDTO.java
  src/main/java/bakery/caker/dto/CommentResponseDTO.java
  src/main/java/bakery/caker/dto/CommentsResponseDTO.java
  src/main/java/bakery/caker/dto/SheetDTO.java
  src/main/java/bakery/caker/dto/SheetResponseDTO.java
  src/main/java/bakery/caker/dto/SheetsResponseDTO.java
  src/main/java/bakery/caker/repository/CommentRepository.java
  src/main/java/bakery/caker/repository/RecommentRepository.java
  src/main/java/bakery/caker/repository/SheetRepository.java
  src/main/java/bakery/caker/service/CommentService.java
  src/main/java/bakery/caker/service/SheetService.java
Labels: enhancement, new feature

#19 Feature/member api
  src/main/java/bakery/caker/controller/MemberController.java
  src/main/java/bakery/caker/dto/MemberResponseDTO.java
  src/main/java/bakery/caker/dto/SessionUserDTO.java
  src/main/java/bakery/caker/service/MemberService.java
  src/main/java/bakery/caker/service/OAuthUserService.java
Labels: enhancement, new feature

#11 Event / Store API 기능.. 개발
  .gitignore
  src/main/java/bakery/caker/controller/EventController.java
  src/main/java/bakery/caker/controller/StoreController.java
  src/main/java/bakery/caker/domain/Event.java
  src/main/java/bakery/caker/domain/Store.java
  src/main/java/bakery/caker/dto/EventRequestDTO.java
  src/main/java/bakery/caker/dto/EventResponseDTO.java
  src/main/java/bakery/caker/dto/StoreRequestDTO.java
  src/main/java/bakery/caker/dto/StoreResponseDTO.java
  src/main/java/bakery/caker/repository/EventRepository.java
  src/main/java/bakery/caker/repository/StoreRepository.java
  src/main/java/bakery/caker/service/EventService.java
  src/main/java/bakery/caker/service/ImageUploadService.java
  src/main/java/bakery/caker/service/StoreService.java
  src/main/resources/application.properties
Labels: enhancement, new feature

#21 Feature/error handle
  src/main/java/bakery/caker/config/CORSConfig.java
  src/main/java/bakery/caker/config/SecurityConfig.java
  src/main/java/bakery/caker/controller/MemberController.java
  src/main/java/bakery/caker/controller/StoreController.java
  src/main/java/bakery/caker/dto/MemberResponseDTO.java
  src/main/java/bakery/caker/exception/CustomException.java
  src/main/java/bakery/caker/exception/ErrorCode.java
  src/main/java/bakery/caker/exception/ErrorResponse.java
  src/main/java/bakery/caker/exception/GlobalExceptionHandler.java
  src/main/java/bakery/caker/exception/tmp.txt
  src/main/java/bakery/caker/service/ImageUploadService.java
  src/main/java/bakery/caker/service/MemberService.java
  src/main/java/bakery/caker/service/OAuthUserService.java
  src/main/java/bakery/caker/service/SheetService.java
Labels: enhancement

#24 Hotfix/authority
  src/main/java/bakery/caker/config/SecurityConfig.java
  src/main/java/bakery/caker/controller/EventController.java
  src/main/java/bakery/caker/controller/StoreController.java
  src/main/java/bakery/caker/exception/GlobalExceptionHandler.java
  src/main/resources/application.properties
Labels: enhancement

#25 Add: 포스트맨 테스트 api 권한 수정
  src/main/java/bakery/caker/config/SecurityConfig.java
Labels: bug, enhancement

#40 Hotfix/event
  src/main/java/bakery/caker/dto/EventResponseDTO.java
  src/main/java/bakery/caker/service/EventService.java
Labels: enhancement

#45 Feature/authorize jwt
  build.gradle
  src/main/java/bakery/caker/config/JwtAuthenticationFilter.java
  src/main/java/bakery/caker/config/LoginUser.java
  src/main/java/bakery/caker/config/LoginUserArgumentResolver.java
  src/main/java/bakery/caker/config/OAuth2SuccessHandler.java
  src/main/java/bakery/caker/config/SecurityConfig.java
  src/main/java/bakery/caker/config/WebConfig.java
  src/main/java/bakery/caker/controller/EventController.java
  src/main/java/bakery/caker/controller/MemberController.java
  src/main/java/bakery/caker/controller/SheetController.java
  src/main/java/bakery/caker/controller/StoreController.java
  src/main/java/bakery/caker/domain/Member.java
  src/main/java/bakery/caker/dto/MemberResponseDTO.java
  src/main/java/bakery/caker/dto/SessionUserDTO.java
  src/main/java/bakery/caker/service/JwtTokenProvider.java
  src/main/java/bakery/caker/service/MemberService.java
  src/main/java/bakery/caker/service/OAuthUserService.java
  src/main/java/bakery/caker/service/StoreService.java
Labels: bug, enhancement

#46 release/authorize 방식 변경
  build.gradle
  src/main/java/bakery/caker/config/JwtAuthenticationFilter.java
  src/main/java/bakery/caker/config/LoginUser.java
  src/main/java/bakery/caker/config/LoginUserArgumentResolver.java
  src/main/java/bakery/caker/config/OAuth2SuccessHandler.java
  src/main/java/bakery/caker/config/SecurityConfig.java
  src/main/java/bakery/caker/config/WebConfig.java
  src/main/java/bakery/caker/controller/EventController.java
  src/main/java/bakery/caker/controller/MemberController.java
  src/main/java/bakery/caker/controller/SheetController.java
  src/main/java/bakery/caker/controller/StoreController.java
  src/main/java/bakery/caker/domain/Member.java
  src/main/java/bakery/caker/dto/MemberResponseDTO.java
  src/main/java/bakery/caker/dto/SessionUserDTO.java
  src/main/java/bakery/caker/service/JwtTokenProvider.java
  src/main/java/bakery/caker/service/MemberService.java
  src/main/java/bakery/caker/service/OAuthUserService.java
  src/main/java/bakery/caker/service/StoreService.java
Labels: enhancement

#47 Hotfix/user domain
  src/main/java/bakery/caker/controller/MemberController.java
  src/main/java/bakery/caker/controller/SheetController.java
  src/main/java/bakery/caker/domain/Member.java
  src/main/java/bakery/caker/dto/MemberResponseDTO.java
  src/main/java/bakery/caker/repository/CommentRepository.java
  src/main/java/bakery/caker/repository/RecommentRepository.java
  src/main/java/bakery/caker/service/CommentService.java
  src/main/java/bakery/caker/service/MemberService.java
  src/main/java/bakery/caker/service/SheetService.java
Labels: bug, enhancement
